services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - mongo
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    command: ["sh", "-c", "python /app/create_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: